### ISSUE TITLE
x/vulndb: potential Go vuln in google.golang.org/api/androidpublisher/v3

### ISSUE THREAD

**Issue by QingsiLiu** [golang/vulndb#1092]
### Description

The specific issues are as follows:
1. "google.golang.org/api/androidpublisher/v3:monetization.subscriptions.basePlans.offers.create"
When this interface is called, no matter what I do, it always returns 500 errors: "googleapi: Error 500: Internal error encountered. backendError"
"Google.golang.org/api/androidpublisher/v3:monetization.subscriptions.basePlans.offers.list"
When this interface is called, when the offer type chooses "acquisitionRule", the "targeting" in the offer structure is always empty, regardless of the settings I choose.
3. "google.golang.org/api/androidpublisher/v3:monetization.subscriptions.basePlans.offers.patch"
When this interface is called and "targeting" is updated, if the type is "acquisitionRule", it always gets an error "googleapi: Error 400: The acquisition targeting rule used an unsupported scope. Must be'This Subscription'or'Any subscription in app', badRequest" has actually set the string correctly
Combining the second and third points, I guess if there are some errors in the back end of the Google API that led to the wrong results in the first point.

### Affected Modules, Packages, Versions and Symbols

```shell
Module: google.golang.org/api
Package: google.golang.org/api/androidpublisher/v3
Versions:
  - Introduced: v0.101.0
Symbols:
  - monetization.subscriptions.basePlans.offers.patch
  - monetization.subscriptions.basePlans.offers.list
  - monetization.subscriptions.basePlans.offers.create
```

### Does this vulnerability already have an associated CVE ID?

I'm not sure

**Comment by neild** [comment]
Thanks for the report.

This doesn't seem to be a security issue, but a problem with using the package. The `golang/vulndb` issue tracker is used for reporting vulnerabilities to the [Go Vulnerability Database](https://go.dev/security/vuln/).

To report an issue with the Google APIs client library, I believe the best path is to open an issue on that project's GitHub repo:
https://github.com/googleapis/google-api-go-client/issues

**Comment by QingsiLiu** [comment]
Sorry I went to the wrong set, thank you for your answer
