### ISSUE TITLE
x/vulndb: potential Go vuln in <package>: <CVE ID>, <GHSA ID>

### ISSUE THREAD

**Issue by khaledalam173** [golang/vulndb#1108]
### CVE ID

bnb1g2mwgryewlfhcjkrfck542z5lazedql99xs793

### GHSA ID

bnb1g2mwgryewlfhcjkrfck542z5lazedql99xs793

### Additional information

New

**Comment by tatianab** [comment]
I'm guessing this was filed by mistake, so I'm closing it out for now. If you'd like to report a public vulnerability in the Go ecosystem, please file another issue with more details so we can evaluate it.
