### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/google/licensecheck

### ISSUE THREAD

**Issue by slumericanB** [golang/vulndb#1134]
### Description

big bad

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

Yes

**Comment by julieqiu** [comment]
Thanks for the report. It looks like github.com/example/module is from the template, and not an actual Go module that can be found at https://pkg.go.dev/github.com/example/module. Closing this issue as out of scope.
