### ISSUE TITLE
x/vulndb: potential Go vuln in bitbucket.org/playsure-go/convert

### ISSUE THREAD

**Issue by yunxi177** [golang/vulndb#1199]
### Description

convert.IntToString not as expected.
Below is the source code implementation
```go
func IntToString(i int) string {
	return strconv.FormatInt(int64(1), 10)
}
```
I think it should be implemented this way
```go
func IntToString(i int) string {
	return strconv.FormatInt(int64(i), 10)
}
```

### Affected Modules, Packages, Versions and Symbols

```shell
Module: bitbucket.org/playsure-go/convert
Package: bitbucket.org/playsure-go/convert
```

### Does this vulnerability already have an associated CVE ID?

I'm not sure

**Comment by tatianab** [comment]
Hi! This issue tracker is for security vulnerabilities in the Go ecosystem. I believe this is a bug, not a security issue. Please report it directly to the maintainers of bitbucket.org/playsure-go/convert.
