### ISSUE TITLE
x/vulndb: suggestion regarding GO-2020-0004

### ISSUE THREAD

**Issue by TamasPergerDWP** [golang/vulndb#1282]
### Report ID

GO-2020-0004

### Suggestion/Comment

There is a typo in the affected symbol name [Auth.ServerHTTP](https://pkg.go.dev/github.com/nanobox-io/golang-nanoauth#Auth.ServerHTTP) -- it should be `Auth.ServeHTTP`

**Comment by tatianab** [comment]
Thanks! This is now fixed.
