### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/vasiunov/features/pkg/snils

### ISSUE THREAD

**Issue by vasiunov** [golang/vulndb#1525]
### Description

Hi to masters of the Goniverse!
I'm still learning golang. However, I really want to be useful to the community and release one module. Unfortunately, I ran into the problem that my repository does not match the requirements.
By comparing the requirements of pkg.go.dev and my repository, I found out that I did everything correctly. However, the package documentation does not appear in pkg.go.dev
![image](https://user-images.githubusercontent.com/112346049/215320716-afac6706-814b-407d-bb6f-b3623f0b58da.png)
![image](https://user-images.githubusercontent.com/112346049/215320949-ac1456f5-aced-4152-ab21-29505f736c23.png)

I hope for your help!
Best regards, Vasiliy Siunov!

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/vasiunov/features/pkg/snils
Package: github.com/vasiunov/features/pkg/snils
Versions:
  - Introduced: 1.0.0
```

### Does this vulnerability already have an associated CVE ID?

I'm not sure

**Comment by timothy-king** [comment]
The vulndb issue tracker is for reporting and tracking security vulnerabilities in go modules. This does not appear to be a security vulnerability. If you are still having problems please file an issue on https://github.com/golang/go/issues. Use the prefix x/pkgsite on the issue.

**Comment by timothy-king** [comment]
You may also find https://pkg.go.dev/about helpful.
