### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/astaxie/beego

### ISSUE THREAD

**Issue by iahim** [golang/vulndb#1528]
### Description

[beego.me](http://beego.me/) points to a casino/slot games website.

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

Yes

**Comment by tatianab** [comment]
Thanks for your report, this is being discussed in https://github.com/golang/go/issues/58328.
