### ISSUE TITLE
x/vulndb: suggestion regarding <GO-XXXX-YYYY>

### ISSUE THREAD

**Issue by ldkingvivi** [golang/vulndb#1561]
### Report ID

/github.com/RobotsAndPencils/go-saml.json

### Suggestion/Comment

I don't think this is the best template to report this issue, but I didn't find a better issue type for this.

Based on the API section in https://go.dev/security/vuln/database , I should I use $base/$module.json List of vulnerability entries for that module. However, for the 4 modules that listed in the index.json, we get 404 for the more specific $modules,json.

/github.com/RobotsAndPencils/go-saml.json
/github.com/AndrewBurian/powermux.json
/github.com/Masterminds/vcs.json
/github.com/Masterminds/goutils.json

Are we suppose to get some content from the /$module.json ?

**Comment by timothy-king** [comment]
https://go.dev/security/vuln/database#api

> To avoid various character set issues, the $module element is encoded using [module.EncodePath](https://pkg.go.dev/golang.org/x/mod/module/#EncodePath).

The URLs for these are:
https://vuln.go.dev/github.com/!robots!and!pencils/go-saml.json
https://vuln.go.dev/github.com/!andrew!burian/powermux.json
https://vuln.go.dev/github.com/!masterminds/goutils.json
https://vuln.go.dev/github.com/!masterminds/vcs.json
