### ISSUE TITLE
x/vulndb: GO-2022-0942 is fixed in v0.8.1 of github.com/graphql-go/graphql

### ISSUE THREAD

**Issue by duncanharris** [golang/vulndb#1722]
### Report ID

GO-2022-0942

### Suggestion/Comment

This is now fixed in v0.8.1 : https://github.com/graphql-go/graphql/releases/tag/v0.8.1

**Comment by timothy-king** [comment]
Fixed in https://go-review.git.corp.google.com/c/vulndb/+/485915. (Not sure why the gopherbot did not pick this up.)
