### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/supabase/cli

### ISSUE THREAD

**Issue by Kaveks** [golang/vulndb#1820]
### Description

My issue arises when I am trying to link local project with remote one

when i run: supabase login 
it prompts for access token but when i generate it from supabase.com then paste on the prompt supabase cli recieves nothing, Its like typing or pasting is not enabled.

please help am using windows 11

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

Yes

**Comment by tatianab** [comment]
Hi @Kaveks,

This issue tracker is reserved for tracking public security vulnerabilities in the Go ecosystem. I'd recommend posting your issue on the https://github.com/supabase/cli/issues tracker.

-Tatiana
