### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/qmuntal/gltf

### ISSUE THREAD

**Issue by pic4xiu** [golang/vulndb#1907]
### Acknowledgement

- [x] The maintainer(s) of the affected project have already been made aware of this vulnerability.

### Description

Processing illegal base64 content may cause gltf to panic, For example, the following gltf file:

```
{"buffers": [
    {
      "uri": "data:application/octet-stream;base64",
      "byteLength": 1
    }
  ]
}
```

When our program calculates the index, the split character is counted by default, and 1 is automatically added, resulting in an out-of-bounds problem in the program.

```
func (b *Buffer) marshalData() ([]byte, error) {
	if !b.IsEmbeddedResource() {
		return nil, nil
	}
	startPos := len(mimetypeApplicationOctet) + 1//startPos is 37
	//But our b.URI is only 36 in length in this processing.
	sl, err := base64.StdEncoding.DecodeString(b.URI[startPos:])
	if len(sl) == 0 || err != nil {
		return nil, err
	}
	return sl, nil
}
```

## what happened

```
❯ go run main.go
panic: runtime error: slice bounds out of range [37:36]

goroutine 1 [running]:
github.com/qmuntal/gltf.(*Buffer).marshalData(0x1400012c1e0)
        /Users/housihan/go/pkg/mod/github.com/qmuntal/gltf@v0.24.0/gltf.go:136 +0xdc
```

### Affected Modules, Packages, Versions and Symbols

```shell
modules:
  - module: github.com/qmuntal/gltf
```

### Fix Commit or Pull Request

https://github.com/qmuntal/gltf/pull/69

**Comment by maceonthompson** [comment]
The Go Vulnerability Database has designated this an in-scope, but non-urgent vulnerability. The identifier GO-2023-1907 has been reserved, but a report will not be published until a fix has been merged. To inform us of a fix, or provide additional information, please reopen and comment on https://github.com/golang/vulndb/issues/1907.

**Comment by pic4xiu** [comment]
Hello, the related bug has been fixed~
