### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0493

### ISSUE THREAD

**Issue by tklauser** [golang/vulndb#2393]
### Report ID

GO-2022-0493

### Suggestion/Comment

The report currently mentions [`Access`](https://pkg.go.dev/golang.org/x/sys/unix#Access) in `golang.org/x/sys/unix` as being affected. However, `Access` [calls](https://cs.opensource.google/go/x/sys/+/refs/tags/v0.15.0:unix/syscall_linux.go;l=27) `Faccessat` with a zero flags parameter and did so since it was added in its current form in 2015 (see go.dev/cl/10032). Thus, I think `Access` is not affected by this vulnerability.

**Comment by tatianab** [comment]
Thank you! You're correct, this has now been fixed in [GO-2022-0493](https://pkg.go.dev/vuln/GO-2022-0493).
