### ISSUE TITLE
x/vulndb: potential Go vuln in jose2go

### ISSUE THREAD

**Issue by mschwager** [golang/vulndb#2409]
### Acknowledgement

- [X] The maintainer(s) of the affected project have already been made aware of this vulnerability.

### Description

The `jose2go` package is subject to a "billion hashes attack" causing denial-of-service when decrypting JWE inputs. This occurs when an attacker can provide a PBES2 encrypted JWE blob with a very large p2c value that, when decrypted, produces a denial-of-service.

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/dvsekhvalnov/jose2go
Package: github.com/dvsekhvalnov/jose2go/jose
Versions:
  - Fixed: 1.6.0
Symbols:
  - jose.Decode
```

### Fix Commit or Pull Request

https://github.com/dvsekhvalnov/jose2go/commit/a4584e9dd7128608fedbc67892eba9697f0d5317

### References

- https://github.com/dvsekhvalnov/jose2go/issues/31
- https://github.com/dvsekhvalnov/jose2go/commit/a4584e9dd7128608fedbc67892eba9697f0d5317
- https://github.com/dvsekhvalnov/jose2go/commit/c5d6a57d4843d9cc91403187d16eea0a70f64db4

**Comment by timothy-king** [comment]
Thank you for the report. We will look into this soon.
