### ISSUE TITLE
x/vulndb: potential Go vuln in <package>

### ISSUE THREAD

**Issue by Hphu2004** [golang/vulndb#2421]
### Acknowledgement

- [X] The maintainer(s) of the affected project have already been made aware of this vulnerability.

### Description

Hpdarker87

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Fix Commit or Pull Request

Google.com

### Additional information

Hpdarker87

**Comment by jba** [comment]
Can you provide more information please?
