### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-2687

### ISSUE THREAD

**Issue by ukai** [golang/vulndb#2700]
### Report ID

GO-2024-2687

### Suggestion/Comment

no need to update grpc-go (google.golang.org/grpc) ?

https://github.com/grpc/grpc-go/releases/tag/v1.62.2
https://github.com/grpc/grpc-go/releases/tag/v1.61.2

**Comment by tatianab** [comment]
Hi, if I understand correctly, you're suggesting that we add `google.golang.org/grpc` to this report. Our philosophy is to only create reports for the core module that contains a vulnerability, and allow scanning tools such as govulncheck to flag the vulnerability in dependencies.

Feel free to re-open if I'm misunderstanding your suggestion.
