### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-2527

### ISSUE THREAD

**Issue by smira** [golang/vulndb#2956]
### Report ID

GO-2024-2527

### Suggestion/Comment

The references security report talks about etcd <= 3.4.9 only https://github.com/etcd-io/etcd/security/advisories/GHSA-5x4g-q5rc-36jp, while Go vuln DB reports "all versions".

**Comment by timothy-king** [comment]
Thank you for the report. We will look into this.

**Comment by harshavardhana** [comment]
https://github.com/golang/vulndb/issues/2952 duplicate of

**Comment by tatianab** [comment]
Closing as duplicate
