### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-2567

### ISSUE THREAD

**Issue by hiohiohio** [golang/vulndb#2966]
### Report ID

GO-2024-2567

### Suggestion/Comment

The affected modules should be `github.com/jackc/pgx/v5` from `v5.0.0-alpha.5` to before v5.5.2
`github.com/jackc/pgx/v4` (and also `github.com/jackc/pgx`?) is not affected by `GO-2024-2567` as the affected `Pipeline.Sync` code is introduced from `v5.0.0-alpha.5` .

ref. https://github.com/jackc/pgx/compare/v5.0.0-alpha.4...v5.0.0-alpha.5#diff-7600c6d53b2bb66dc26f15ff10fb080ad09158eea6e7562a8dc1db33d1ea2abfR1781

**Comment by tatianab** [comment]
Hi, thanks for the suggestion. Fix is in the works.
