### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0869

### ISSUE THREAD

**Issue by dornimaug** [golang/vulndb#3084]
### Report ID

GO-2022-0869

### Suggestion/Comment

Report says all 2.x versions in github.com/argoproj/argo-cd/v2 are affected, but the original advisory only refers to "All versions prior to 1.7.13 and 1.8.6".

**Comment by tatianab** [comment]
Thanks for reporting this, will fix!

BTW the reason for this error is that https://github.com/advisories/GHSA-qq5v-f4c3-395c mistakenly lists v2 instead of v1 as affected.
