### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-3166

### ISSUE THREAD

**Issue by bobcallaway** [golang/vulndb#3198]
### Report ID

GO-2024-3166

### Suggestion/Comment

Please update the range for this report to match the revised value in the CVE record (discussion in GHSA can be found [here](https://github.com/github/advisory-database/pull/4893#issuecomment-2407420136))

go-tuf < 2.0 is not vulnerable.

Thanks!

**Comment by xnox** [comment]
Please remove row [github.com/theupdateframework/go-tuf](https://pkg.go.dev/github.com/theupdateframework/go-tuf)
all versions, no known fixed

Keep /v2 row as is.

**Comment by maceonthompson** [comment]
Thanks for the suggestion! Updated.
