### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-3189

### ISSUE THREAD

**Issue by kcalvinalvin** [golang/vulndb#3206]
### Report ID

GO-2024-3189

### Suggestion/Comment

The vulndb incorrectly lists that all versions are affected with no fix. The fix is included in the latest version `v0.24.2-beta` as stated in: https://github.com/btcsuite/btcd/security/advisories/GHSA-27vh-h6mc-q6g8

**Comment by tatianab** [comment]
Thanks! Fix should show up soon.
