### ISSUE TITLE
x/vulndb: GO-2024-3167 shouldn't flag mark github.com/golang-fips/openssl/v2

### ISSUE THREAD

**Issue by qmuntal** [golang/vulndb#3229]
### Report ID

GO-2024-3167

### Suggestion/Comment

`github.com/golang-fips/openssl/v2` was initially flagged in `GHSA-3h3x-2hwv-hr52`, but only `v1` is affected by the vulnerability. I've corrected the error in https://github.com/github/advisory-database/pull/4950.

**Comment by tatianab** [comment]
Hi @qmuntal, thanks for your report. Fix should be in soon.
