### ISSUE TITLE
x/vulndb: suggestion regarding GO-2024-2920

### ISSUE THREAD

**Issue by StevenACoffman** [golang/vulndb#3247]
### Report ID

GO-2024-2920

### Suggestion/Comment

This vulnerability is only for versions prior to v2.5.14 and was fixed in v2.5.14 and later

**Comment by tatianab** [comment]
Hi @StevenACoffman, thanks for your report. Does the vulnerability apply to v1 (github.com/vektah/gqlparser) or only v2?

**Comment by StevenACoffman** [comment]
Only old versions of v2. 
go-vulncheck should also not report anything for a project using v2.5.14 or newer github.com/vektah/gqlparser/v2
or the extremely old v1, which likely has completely different problems.
