### ISSUE TITLE
x/vulndb: potential Go vuln in go.etcd.io/etcd

### ISSUE THREAD

**Issue by jba** [golang/vulndb#5]
Now used to track GO-2020-0005.

----

old description:

The DB is [constructed assuming that package import paths are unique](https://github.com/golang/vulndb/blob/master/cmd/gendb/main.go#L74). But it's possible to have two different packages with the same import path, even at the same version. Example:

https://pkg.go.dev/github.com/hashicorp/vault@v1.0.1/api
https://pkg.go.dev/github.com/hashicorp/vault/api@v1.0.1

**Comment by pombredanne** [comment]
@jba what should be the "canonical" form?

**Comment by jba** [comment]
In pkg.go.dev we use the form you see above, where the version attaches to the module path. That is Go-specific, though.

**Comment by julieqiu** [comment]
Moved to https://github.com/golang/go/issues/50005.

**Comment by tatianab** [comment]
Review for appropriate use of [alias](https://ossf.github.io/osv-schema/#aliases-field) vs [related](https://ossf.github.io/osv-schema/#related-field)

**Comment by pombredanne** [comment]
@tatianab you wrote:

> Review for appropriate use of [alias](https://ossf.github.io/osv-schema/#aliases-field) vs [related](https://ossf.github.io/osv-schema/#related-field)

Can you elaborate what you mean?

**Comment by tatianab** [comment]
Hi, I took over this issue to track work on GO-2020-0005, the original issue is now tracked in https://github.com/golang/go/issues/50005.

(The comment I made refers to a clarification in the OSV spec of the meaning of alias vs related https://github.com/ossf/osv-schema/pull/193. It is just a reminder for me to go back and review all our reports that list 2 or more CVEs as an alias).
