### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pkg/sftp

### ISSUE THREAD

**Issue by Shikha13dubey** [golang/vulndb#948]
### Description

Hello,
I am facing an issue while making go build for our project. It is asking for .zip file instead of .mod.
Error :-
go: downloading github.com/jmespath/go-jmespath v0.4.0conf/utils/connectVM.go:17:2: zip for github.com/pkg/sftp@v1.13.1 has unexpected file sftp-1.13.1/
Thanks 

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

No

### Additional information

Hello,
I am facing an issue while making go build for our project. It is asking for .zip file instead of .mod.
Error :-
go: downloading github.com/jmespath/go-jmespath v0.4.0conf/utils/connectVM.go:17:2: zip for github.com/pkg/sftp@v1.13.1 has unexpected file sftp-1.13.1/
Thanks

**Comment by julieqiu** [comment]
This issue tracker is just use for reports in https://vuln.go.dev. In the future, feel free to file an issue at https://golang.org/s/govulncheck-feedback for issues with the package/tool.

Moved this to https://github.com/golang/go/issues/54524.
