### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0493

### ISSUE THREAD

**Issue by prattmic** [golang/vulndb#966]
### Report ID

GO-2022-0493

### Suggestion/Comment

This report lists [`unix.Access`](https://github.com/golang/vulndb/blob/master/data/reports/GO-2022-0493.yaml#L21) as affected. Per golang/go#54889, `Access` is not actually affected.

golang/go#54889 is the more general issue here, but since the caller (`Access`) is in the same package, I figure that for this specific case there may be a way for you to explicitly annotate `Access` as not affected.

**Comment by tatianab** [comment]
Thanks for your suggestion! We'll take a look.

Parent issue #493

**Comment by tatianab** [comment]
I am closing this for now as we currently don't have a way to annotate the report. If we fix #493, we will update the report accordingly.
