### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0646

### ISSUE THREAD

**Issue by jasdel** [golang/vulndb#967]
### Report ID

GO-2022-0646

### Suggestion/Comment

The aws-sdk-go [release](https://aws.amazon.com/blogs/developer/updates-to-the-amazon-s3-encryption-client/) [v1.34.0](https://github.com/aws/aws-sdk-go/releases/v1.34.0) updated the `github.com/aws/aws-sdk-go/service/s3/s3crypto` package, deprecating the `EncryptionClient` vulnerable type. Adding `EncryptionClientV2` which is not vulnerable. The CVE notices calls this out, but flags the package as vulnerable with no known fix. Requesting that packages after `v1.34.0` be updated since mitigations have been added, and the vulnerable types have been deprecated.

**Comment by neild** [comment]
The [report for GO-2022-0646](https://go.googlesource.com/vulndb/+/refs/heads/master/data/reports/GO-2022-0646.yaml) lists the `NewEncryptionClient` and `NewDecryptionClient` symbols as vulnerable at all versions, which they are. Updating to `v1.34.0` isn't sufficient to address this vulnerability; you also need to switch to `EncryptionClientV2`. And actually that isn't sufficient, either; you need to reencrypt any existing data encrypted by the previous client using either `AES-CBC` or the `KMS` option.

(Arguably, we shouldn't list `NewDecryptionClient` as vulnerable, but I figured usage of the older decryption client was a strong signal that vulnerable encryption is in use.)

`govulncheck` will not flag programs that use only `NewEncryptionClientV2`.

The [pkgsite page](https://pkg.go.dev/vuln/GO-2022-0646) doesn't list the vulnerable symbol information, however, so it's not clear that the vulnerability only applies to specific symbols. This is https://go.dev/issue/54812.

**Comment by jasdel** [comment]
Thanks for the update. Being able to enumerate the vulnerable symbols would be very helpful in communicating the scope of the issue.

Agree updating the the v2 version of both of these types is the best forward path. If the vulnerability could be scoped to the impacted symbols, I think it would help communicate the impact, and mitigation as not vulnerable.
