### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/Azure/azure-kusto-go/kusto

### ISSUE THREAD

**Issue by 1730735794** [golang/vulndb#990]
### Description

cannot use `time.Now()` as parameters' default value;
 such as
```
     timeFilter, err := kusto.NewDefinitions().With(
		kusto.ParamTypes{
			"beginTime": kusto.ParamType{Type: types.DateTime, Default: time.Now()},
			"endTime":   kusto.ParamType{Type: types.DateTime, Default: time.Now()},
			"name":      kusto.ParamType{Type: types.String, Default: ""},
			"mess":      kusto.ParamType{Type: types.String, Default: ""},
		},
	)
```
it can be send to kusto, but will get a 400 bad request.
```
"@message": "Syntax error: SYN0002: A recognition error occurred. [line:position=1:50]",
```

### Affected Modules, Packages, Versions and Symbols

```shell
Module: github.com/example/module
Package: github.com/example/module/package
Versions:
  - Introduced: 1.2.0
  - Fixed: 1.2.4
Symbols:
  - aFunction
  - SomeType.AMethod

Module: github.com/example/module/v2
Package: github.com/example/module/v2/package
Versions:
  - Fixed: 2.4.5
Symbols:
  - anotherFunction
```

### Does this vulnerability already have an associated CVE ID?

I'm not sure

**Comment by tatianab** [comment]
Hi, thanks for filing an issue!

I have a couple questions: 1) has this issue been reported to the maintainer of the package? (if so, could you link a tracking issue?, and 2) could you give more detail about why this issue represents a security vulnerability?

**Comment by tatianab** [comment]
Hi again, I am closing this issue for now as it appears to be out of scope for our issue tracker. Please re-open with a comment if you believe this is an error.
