### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0988

### ISSUE THREAD

**Issue by pjuarezd** [golang/vulndb#994]
### Report ID

GO-2022-0988

### Suggestion/Comment

Vulnerability fix is not listed as available in 1.18.6 per this release
https://groups.google.com/g/golang-announce/c/x49AQzIVX-s

GO-2022-0988 should also list 1.18.6 as fixed

**Comment by tatianab** [comment]
Hi, thanks for your report! The announcement did not clarify this, but the JoinPath API was actually introduced in Go 1.19, so the vulnerability was not present in Go 1.18 or any earlier version. 

Feel free to re-open this if you have further questions/comments.
