### ISSUE TITLE
x/vulndb: suggestion regarding GO-2022-0969

### ISSUE THREAD

**Issue by pjuarezd** [golang/vulndb#996]
### Report ID

GO-2022-0969

### Suggestion/Comment

vulncheck utility stills marks the 1.18.6 as vulnerable despite this vuln was [resolved in 1.18.6](https://groups.google.com/g/golang-announce/c/x49AQzIVX-s)
Perhaps is due to the report missing the `introduced` [field](https://github.com/golang/vulndb/blob/f5a54a5a08763d2d345363317b3c1b3909d970bb/data/reports/GO-2022-0969.yaml#L4)?

**Comment by zpavlinovic** [comment]
Thanks for bringing this up. This is a duplicate of #55035. I will close it for now, but we can open it again if the fix for that issue does not help.
